#
# CMakeIt - a collection of CMake modules to build programs from 'Visual Studio'-like 
# projects, and well-structure project layouts (public and private include folders,
# source folders), using CMake build system. Also features pre compiled headers
# support, unit tests, installation ('make install' style), packaging, etc.
#
# Copyright (C) 2013, Fornazin & Fornazin Consultoria em Informática Ltda
#
# This library is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software 
# Foundation; either version 3 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful, but WITHOUT ANY 
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
# PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along 
# with this library; if not, please write to the Free Software Foundation, Inc., 
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

#
# cmakeit_module_subtree_layout_detection.cmake - CMakeIt module subtree layout detection
#

if((NOT CMAKEIT_SOURCES_LAYOUT) AND (CMAKEIT_SUBMODULE_NAME))

	if((IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/include/private/${CMAKEIT_MODULE_NAME}/${CMAKEIT_SUBMODULE_NAME}") AND
		(IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/include/public/${CMAKEIT_MODULE_NAME}/${CMAKEIT_SUBMODULE_NAME}") AND
		(IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/src/${CMAKEIT_MODULE_NAME}/${CMAKEIT_SUBMODULE_NAME}"))

		set(CMAKEIT_MODULE_PRIVATE_HEADER_DIR "${CMAKE_CURRENT_SOURCE_DIR}/include/private")
		set(CMAKEIT_MODULE_PUBLIC_HEADER_DIR "${CMAKE_CURRENT_SOURCE_DIR}/include/public")
		set(CMAKEIT_MODULE_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/src")

		set(CMAKEIT_SOURCES_LAYOUT ${CMAKEIT_SOURCES_LAYOUT_PRIVATE_PUBLIC_HEADER_AND_SOURCE_DIRECTORIES})

	endif()

endif()

if((NOT CMAKEIT_SOURCES_LAYOUT) AND (CMAKEIT_MODULE_NAME))

	if((IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/include/private/${CMAKEIT_MODULE_NAME}") AND
		(IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/include/public/${CMAKEIT_MODULE_NAME}") AND
		(IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/src/${CMAKEIT_MODULE_NAME}"))

		set(CMAKEIT_MODULE_PRIVATE_HEADER_DIR "${CMAKE_CURRENT_SOURCE_DIR}/include/private")
		set(CMAKEIT_MODULE_PUBLIC_HEADER_DIR "${CMAKE_CURRENT_SOURCE_DIR}/include/public")
		set(CMAKEIT_MODULE_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/src")

		set(CMAKEIT_SOURCES_LAYOUT ${CMAKEIT_SOURCES_LAYOUT_PRIVATE_PUBLIC_HEADER_AND_SOURCE_DIRECTORIES})

	endif()

endif()

if(NOT CMAKEIT_SOURCES_LAYOUT)

	if((IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/include/private") AND
		(IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/include/public") AND
		(IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/src"))

		set(CMAKEIT_MODULE_PRIVATE_HEADER_DIR "${CMAKE_CURRENT_SOURCE_DIR}/include/private")
		set(CMAKEIT_MODULE_PUBLIC_HEADER_DIR "${CMAKE_CURRENT_SOURCE_DIR}/include/public")
		set(CMAKEIT_MODULE_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/src")

		set(CMAKEIT_SOURCES_LAYOUT ${CMAKEIT_SOURCES_LAYOUT_PRIVATE_PUBLIC_HEADER_AND_SOURCE_DIRECTORIES})

	endif()

endif()

if((NOT CMAKEIT_SOURCES_LAYOUT) AND (CMAKEIT_SUBMODULE_NAME))

	if((IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/include/${CMAKEIT_MODULE_NAME}/${CMAKEIT_SUBMODULE_NAME}") AND
		(IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/src/${CMAKEIT_MODULE_NAME}/${CMAKEIT_SUBMODULE_NAME}"))

		set(CMAKEIT_MODULE_PRIVATE_HEADER_DIR "${CMAKE_CURRENT_SOURCE_DIR}/src")
		set(CMAKEIT_MODULE_PUBLIC_HEADER_DIR "${CMAKE_CURRENT_SOURCE_DIR}/include")
		set(CMAKEIT_MODULE_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/src")

		set(CMAKEIT_SOURCES_LAYOUT ${CMAKEIT_SOURCES_LAYOUT_PUBLIC_HEADER_AND_SOURCE_DIRECTORIES})

	endif()

endif()

if((NOT CMAKEIT_SOURCES_LAYOUT) AND (CMAKEIT_MODULE_NAME))

	if((IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/include/${CMAKEIT_MODULE_NAME}") AND
		(IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/src/${CMAKEIT_MODULE_NAME}"))

		set(CMAKEIT_MODULE_PRIVATE_HEADER_DIR "${CMAKE_CURRENT_SOURCE_DIR}/src")
		set(CMAKEIT_MODULE_PUBLIC_HEADER_DIR "${CMAKE_CURRENT_SOURCE_DIR}/include")
		set(CMAKEIT_MODULE_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/src")

		set(CMAKEIT_SOURCES_LAYOUT ${CMAKEIT_SOURCES_LAYOUT_PUBLIC_HEADER_AND_SOURCE_DIRECTORIES})

	endif()

endif()

if(NOT CMAKEIT_SOURCES_LAYOUT)

	if((IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/include") AND
		(IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/src"))

		set(CMAKEIT_MODULE_PRIVATE_HEADER_DIR "${CMAKE_CURRENT_SOURCE_DIR}/src")
		set(CMAKEIT_MODULE_PUBLIC_HEADER_DIR "${CMAKE_CURRENT_SOURCE_DIR}/include")
		set(CMAKEIT_MODULE_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/src")

		set(CMAKEIT_SOURCES_LAYOUT ${CMAKEIT_SOURCES_LAYOUT_PUBLIC_HEADER_AND_SOURCE_DIRECTORIES})

	endif()

endif()

if(NOT CMAKEIT_SOURCES_LAYOUT)

	if((IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/include"))

		set(CMAKEIT_MODULE_PRIVATE_HEADER_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
		set(CMAKEIT_MODULE_PUBLIC_HEADER_DIR "${CMAKE_CURRENT_SOURCE_DIR}/include")
		set(CMAKEIT_MODULE_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")

		set(CMAKEIT_SOURCES_LAYOUT ${CMAKEIT_SOURCES_LAYOUT_PUBLIC_HEADER_DIRECTORY})

	endif()

endif()

if(NOT CMAKEIT_SOURCES_LAYOUT)

	if((IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/src"))

		set(CMAKEIT_MODULE_PRIVATE_HEADER_DIR "${CMAKE_CURRENT_SOURCE_DIR}/src")
		set(CMAKEIT_MODULE_PUBLIC_HEADER_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
		set(CMAKEIT_MODULE_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/src")

		set(CMAKEIT_SOURCES_LAYOUT ${CMAKEIT_SOURCES_LAYOUT_PUBLIC_SOURCE_DIRECTORY})

	endif()

endif()

if(NOT CMAKEIT_SOURCES_LAYOUT)

	if(CMAKEIT_MODULE_TYPE STREQUAL ${CMAKEIT_MODULE_TYPE_LIBRARY})

		unset(CMAKEIT_MODULE_PRIVATE_HEADER_DIR)
		set(CMAKEIT_MODULE_PUBLIC_HEADER_DIR "${CMAKE_CURRENT_SOURCE_DIR}")

	else()

		set(CMAKEIT_MODULE_PRIVATE_HEADER_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
		unset(CMAKEIT_MODULE_PUBLIC_HEADER_DIR)
		
	endif()

	set(CMAKEIT_MODULE_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")

	set(CMAKEIT_SOURCES_LAYOUT ${CMAKEIT_SOURCES_LAYOUT_ENTIRE_DIRECTORY})

endif()

if(CMAKEIT_MODULE_PRIVATE_HEADER_DIR)
	string(REPLACE ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKEIT_MODULE_OUTPUT_CONFIGURED_DIR} CMAKEIT_MODULE_OUTPUT_CONFIGURED_PRIVATE_HEADER_DIR ${CMAKEIT_MODULE_PRIVATE_HEADER_DIR})
else()
	unset(CMAKEIT_MODULE_OUTPUT_CONFIGURED_PRIVATE_HEADER_DIR)
endif()

if(CMAKEIT_MODULE_PUBLIC_HEADER_DIR)
	string(REPLACE ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKEIT_MODULE_OUTPUT_CONFIGURED_DIR} CMAKEIT_MODULE_OUTPUT_CONFIGURED_PUBLIC_HEADER_DIR ${CMAKEIT_MODULE_PUBLIC_HEADER_DIR})
else()
	unset(CMAKEIT_MODULE_OUTPUT_CONFIGURED_PUBLIC_HEADER_DIR)
endif()

if(CMAKEIT_MODULE_SOURCE_DIR)
	string(REPLACE ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKEIT_MODULE_OUTPUT_CONFIGURED_DIR} CMAKEIT_MODULE_OUTPUT_CONFIGURED_SOURCE_DIR ${CMAKEIT_MODULE_SOURCE_DIR})
else()
	unset(CMAKEIT_MODULE_OUTPUT_CONFIGURED_SOURCE_DIR)
endif()

if(NOT CMAKEIT_HIDE_BANNER)  
	message(STATUS "| +-- Directory structure: ${CMAKEIT_SOURCES_LAYOUT}")
endif()
